### ISSUE TITLE
what is the M_PI variable in the file DiscreteElasticRods.cpp?

### ISSUE THREAD

**Issue by mnswwz** [Zhecheng-Wang/Discrete-Elastic-Rods#1]
![image](https://github.com/Zhecheng-Wang/Discrete-Elastic-Rods/assets/22149035/2c6fd9ff-7ee8-4ba0-83fe-906a58a9d8a1)

The varibale M_PI in the file DiscreteElasticRods.cpp cannot locate its declaration. Can you give some more details?

**Comment by Zhecheng-Wang** [comment]
Hi, the M_PI is simply the pi constant. See https://stackoverflow.com/questions/1727881/how-to-use-the-pi-constant-in-c.

I have pushed a commit to main branch to define the PI constant and fix some bugs.
