### ISSUE TITLE
polyscope dependency problem

### ISSUE THREAD

**Issue by mnswwz** [Zhecheng-Wang/Discrete-Elastic-Rods#2]
Can you upload the polyscope as a thirdparty which will make the repository much more convenient to use? When I came to compile the   polyscope, I found it was not that simple to compile.

**Comment by mnswwz** [comment]
When I came to compile the polyscope, I have to compile the imgui, which was found not a cmake project.

**Comment by Zhecheng-Wang** [comment]
Please follow the [polyscope building instructions](https://polyscope.run/building/) and clone the polyscope repo recursively. Imgui is downloaded as a git submodule of polyscope.
